### PR TITLE
update files with info for WDMAM 2.0

### PR DESCRIPTION
**Pull request by Esteban82**
I update the file to fix the issue describe by seisman (https://github.com/GenericMappingTools/gmtserver-admin/pull/204#issuecomment-1670704020). 

Hopefully fix this issue [2622 in pygmt](https://github.com/GenericMappingTools/pygmt/issues/2622)?

### CODE REVIEW

**Comment by Esteban82** [comment]
I have a doubt. Is it neccesary to update the `earth_wdmam_server.txt` file? Or just only `gmt_data_server.txt`?

**Comment by seisman** [comment]
> I have a doubt. Is it neccesary to update the `earth_wdmam_server.txt` file? Or just only `gmt_data_server.txt`?

The `gmt_data_server.txt` is built from these `*_server.txt` files by running `make server-info`.

**Comment by Esteban82** [comment]
Ok. So that is only done by someone, right? Isn't there a script that does it automatically via contrab or something like that?

**Comment by seisman** [comment]
> So that is only done by someone, right?

I think yes.

**Comment by seisman** [comment]
> > So that is only done by someone, right?
> 
> I think yes.

It seems the `gmt_data_server.txt` file was updated in PR https://github.com/GenericMappingTools/gmtserver-admin/pull/206, which shouldn't because the  new data is not released.

BTW, why not just release the WDMAM 2.0 dataset (i.e., copy the new data files to the oceanic server)?

**Comment by Esteban82** [comment]
You mean WDMAM 2.1, right?
I have only copy data to the test server. I think I could try to do it to the main server.

**Comment by seisman** [comment]
> You mean WDMAM 2.1, right?

Yes.

**Comment by Esteban82** [comment]
I want to do it but I am not very confident how to update the main server. 
@PaulWessel what do you think? Should I do it? Any suggestions?

**Comment by PaulWessel** [comment]
Let's see:

make server-info builds an updated gmt_data_server.txt file and overwrites what is in information dir.  So if we just want to release WDMAM then I think we get problems because other info files have been updated? Perhaps you need to

1. Create the correct server file manually (old file, then update WDMAM).
2. Copy and place the updated gmt_data_server.txt file on the oceania server
3. As soon as possible afterwards, cp the test files for WDMAM over and overwrite/replaces 2.0

I think you can do this, not many are using these files so if we have a problem we can just fix.

**Comment by Esteban82** [comment]
> So if we just want to release WDMAM then I think we get problems because other info files have been updated?

Yes, and there are even new files from a long time (four to months) but it didn't affect other datasets. 

For example, I check @earth_faa. Grdcut says **Gravity Anomalies v32** while grdinfo says **grav_31.1.nc**.

### Full script
```
gmt grdcut @earth_faa_06m_g -R10/13/-60/-58 -Gout.nc
gmt grdinfo out.nc

grdcut [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]
grdcut [NOTICE]: IGPP Earth Free Air Gravity Anomalies v32 at 6x6 arc minutes reduced by Gaussian Cartesian filtering (11 km fullwidth) [Sandwell et al., 2019].
grdcut [NOTICE]:   -> Download grid file [7.6M]: earth_faa_06m_g.grd
out.nc: Title: Produced by grdcut
out.nc: Command: gmt grdcut @earth_faa_06m_g -R10/13/-60/-58 -Gout.nc
out.nc: Remark: Reduced by Gaussian Cartesian filtering (11.2 km fullwidth) from /tmp/29255/grav_31.1.nc [Sandwell et al., 2019; https://doi.org/10.1016/j.asr.2019.09.011]
out.nc: Gridline node registration used [Geographic grid]
out.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
out.nc: x_min: 10 x_max: 13 x_inc: 0.1 (6 min) name: longitude n_columns: 31
out.nc: y_min: -60 y_max: -58 y_inc: 0.1 (6 min) name: latitude n_rows: 21
out.nc: v_min: -38.5249938965 v_max: 17.549987793 name: faa (mGal)
out.nc: scale_factor: 1 add_offset: 0
out.nc: format: classic
out.nc: Default CPT: @earth_faa.cpt
```

**Comment by Esteban82** [comment]
> * Copy and place the updated gmt_data_server.txt file on the oceania server

For what I understand of this [script](https://github.com/GenericMappingTools/gmtserver-admin/blob/master/scripts/srv_do_updates.sh) I think that I should update the gmt_data_server.txt in this repo (not in the server). I don't remember copying any file to the data server.

I think it would be easier if I just update all the grids in the main server.

**Pull request merged**
