### PR TITLE
Add file with top 12 cities metadata

### PR DESCRIPTION
**Pull request by PaulWessel**
Metadata for the 12 largest cities in the world. To be used in ex53.

### CODE REVIEW

**Comment by meghanrjones** [comment]
I assume you tested this with the ex53 draft script? I am asking because it looks like there could be different separators in the file and a character that does not render well on my screen.

**Comment by PaulWessel** [comment]
The script works fine for me.  Doing `od -c` on the file does not show anything funny regarding separators, just tabs.  it does have a code for Sao Paulo which plots as expected when I run the script (probably requires ISOLatin1+ which we set when running tests?

**Review by meghanrjones — APPROVED** [review]

**Comment by PaulWessel** [comment]
We should check that the new files shows up in cache when the server runs the script at the full hour.  I remember there were problems last time and it did not smoothly update.

**Comment by PaulWessel** [comment]
`gmt info @Top12Cities.txt` now worked for me so cache server is updated.

**Pull request merged**
