### PR TITLE
Use tab separation for cache/hotspots.txt

### PR DESCRIPTION
**Pull request by meghanrjones**
This PR updates the separators for the hotspots.txt to be tabs because the irregular number of spaces complicates using the file for PyGMT tests/examples (e.g., https://github.com/GenericMappingTools/pygmt/pull/1386).

Of course, feel free to comment if there is a reason for the current format or if this will cause problems for core GMT or the other wrappers.

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]

**Comment by seisman** [comment]
The latest cron job on the GMT server failed to update the caches.

It seems that all the files in the `gmtserver-admin` directory on the server were deleted but there are also a lot of untracked files. Did anyone manually change the files on the server?

**Comment by meghanrjones** [comment]
I haven't edited any files on the server. Could this be related to all the problems that were happening on GitHub this morning (https://www.githubstatus.com/incidents/rmfrw9dfbtbp)?

**Comment by seisman** [comment]
That's possible. I will try to fix it manually.

**Comment by seisman** [comment]
I'm afraid there are some permission issues on the GMT server. I no longer have the write permission to any files on the server.

**Comment by PaulWessel** [comment]
Strange, I have not logged into the server in weeks.  We added a file to the cache yesterday but via git as usual.

**Comment by seisman** [comment]
FYI, I just fixed the git problem on the GMT server, and now the local copy on the GMT server is up-to-date with the remote copy.

The caches will be updated on 14:00 HST, and I will check it later and let you know if it works.

**Comment by meghanrjones** [comment]
> FYI, I just fixed the git problem on the GMT server, and now the local copy on the GMT server is up-to-date with the remote copy.
> 
> The caches will be updated on 14:00 HST, and I will check it later and let you know if it works.

Thank you!

**Pull request merged**
