### PR TITLE
Update DOI and date for age grids

### PR DESCRIPTION
**Pull request by PaulWessel**
Must separately run **gmt grdedit** on the age nc files to update the remarks with the DOI.  Probably do that first, them merge this PR.  I think this script should work.  I tested it on the files in my private staging area where I built the original files in July:

```
#!/bin/bash
# Run this from server dir which has earth beneath it:

ls earth/earth_age/*.grd > /tmp/t.lis
while read file; do
	printf "\n%s:\n" $file
	old_remark=$(gmt grdinfo $file | grep Remark | awk -F': ' '{print $3}')
	new_remark=$(echo ${old_remark} | sed -e 'sXin reviewXhttp://dx.doi.org/110.1029/2020GC009214Xg')
	echo "Old remark: ${old_remark}"
	echo "New remark: ${new_remark}"
	gmt grdedit $file -D+r\"${new_remark}\"
done < /tmp/t.lis
```

However, got this problem with the master (1m) file:

earth/earth_age/earth_age_01m_g.grd:
```
Old remark: Reformatted from master file https://earthbyte.org/webdav/ftp/earthbyte/agegrid/2020/Grids/age.2020.1.GTS2012.1m.nc [Seton et al., 2020; in review]
New remark: Reformatted from master file https://earthbyte.org/webdav/ftp/earthbyte/agegrid/2020/Grids/age.2020.1.GTS2012.1m.nc [Seton et al., 2020; http://dx.doi.org/110.1029/2020GC009214]
grdedit [WARNING]: Remark string exceeds upper length of 160 characters (truncated)
```

So we need to be careful with making sure the remark is < 160.  I guess I can remove some fluff from this to make sure, e.g.,

```
echo "Orig is https://earthbyte.org/webdav/ftp/earthbyte/agegrid/2020/Grids/age.2020.1.GTS2012.1m.nc [Seton et al., 2020; http://dx.doi.org/110.1029/2020GC009214]" | wc -c
157
```

Add safety valve:

```
ls earth/earth_age/*.grd > /tmp/t.lis
while read file; do
	printf "\n%s:\n" $file
	old_remark=$(gmt grdinfo $file | grep Remark | awk -F': ' '{print $3}')
	new_remark=$(echo ${old_remark} | sed -e 'sXin reviewXhttp://dx.doi.org/110.1029/2020GC009214Xg')
	echo "Old remark: ${old_remark}"
	echo "New remark: ${new_remark}"
	if [ $(echo $new_remark | awk '{print length($0}') -ge 160 ]; then
		echo "Warning, new remark is too long for the 160 character attribute, shorten manually"
	else
		gmt grdedit $file -D+r"${new_remark}"
	fi
done < /tmp/t.lis
```

Comments on this, @seisman?

### CODE REVIEW

**Comment by PaulWessel** [comment]
Oh, the master will be tiled anyway so that .grd is not on the server.  I think the above will work fine on the remaining courser grd files

**Comment by seisman** [comment]
There must be some typos in your script. 
```
if [ $(echo $new_remark | awk '{print length($0}') -ge 160 ]; then
```

and the doi (http://dx.doi.org/110.1029/2020GC009214) is wrong.

**Comment by PaulWessel** [comment]
Yes, missing end parenthesis, sorry:

	`if [ $(echo $new_remark | awk '{print length($0)}') -ge 160 ]; then`

But the script I will run wont have that test at all since only the master full resolution intermediate grid has that remark but it is tiled so not placed on the server in that format.

I fixed the DOI line

`	new_remark=$(echo ${old_remark} | sed -e 'sXin reviewXhttp://dx.doi.org/10.1029/2020GC009214Xg')
`

**Review by seisman — APPROVED** [review]

**Comment by PaulWessel** [comment]
I think this is OK to add that script to the folder so it does not get lost in case we need it again.  I will wait for server to update, then log in and manually run that script.

**Pull request merged**
