### PR TITLE
Geologists data

### PR DESCRIPTION
**Pull request by PaulWessel**
Add this file also, used by the 1st example in the paperl
@seisman, yesterday I think I tried to commit a small change directly to master but it somehow failed, and now it lists these two commits in addition to the one I want:
7c70870 abd d7d617f
Also these show up as uncommitted in my Desktop Git GUI and I dont know how to get rid of them . Need your git magic advice.

### CODE REVIEW

**Comment by seisman** [comment]
Is everything OK if you checkout your master branch and update it?

**Comment by PaulWessel** [comment]
I just ran git pull in gmtserver-admin and it popped up a file in my editor called MERGE_MSG taht contains

Merge branch 'master' of https://github.com/GenericMappingTools/gmtserver-admin
# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.

Since everything is (I think) find in github, should I just delete my working copy and clone again?

**Comment by seisman** [comment]
> should I just delete my working copy and clone again?

Yes, it's easier.

**Comment by PaulWessel** [comment]
OK, back to normal, Thanks.

**Pull request merged**
