### PR TITLE
Adding new data set Earth distances (to GSHHG)

### PR DESCRIPTION
**Pull request by PaulWessel**
I have added one more dataset: The grid with distances from any node to the nearest coastline, in km.  I did this 12 years or more ago and will eventually rerun that calculation up to 15s, but it takes a very long time so we start with this grid, used in these two:

1.  https://doi.org/10.5670/oceanog.2010.32
2. https://doi.org/10.2478/s11600-010-0038-1

Perhaps we can use the OSM shoreline but will take even longer. So far:

1. Added each_dist.recipe and placed the original source (with proper permissions) on the SOEST ftp server.
2. Added required targets to the Makefile.
3. Ran make earth-dist to populate the staging dir
4. Ran make place-earth-dist to put them on candidate.
5.  Ran make candidate-info to update gmt_data_server.txt on candidate only.
6. Resurrected my 2010 CPT that was used and called it @earth_dist.cpt and added to cache.

I will finish up what this means for remote_dataset but need stuff to update on the server cache (the cpt)/

### CODE REVIEW

**Comment by anbj** [comment]
This is very convenient. What coast line resolution is used?

**Comment by PaulWessel** [comment]
Full resolution but for now, because we are using 16-bits grids the precision of the distances is 80 m.  If you plan to use it for small areas then it is not so great, but it is also just a 01m grid.

**Comment by anbj** [comment]
Thanks!

**Review by Esteban82 — APPROVED** [review]

**Comment by Esteban82** [comment]
I fix a typo in the DOI in the cpt.

**Pull request merged**
