### PR TITLE
Add PLANET in server-release.sh

### LINKED ISSUE #222: server-release.sh doesn't work for a single data set
@PaulWessel I run:

`make server-release` with `mars_relief` (as suggested by the text in the terminal).

```
$ make server-release
scripts/server-release.sh
server-release.sh: Enter a specific data set (e.g., mars_relief) or hit return for all data on the candidate: mars_relief 
```
In the first command of `/tmp/release.sh`, the names of both paths are wrong.

```
# 1. Issue rsync command
rsync -al /export/gmtserver/gmt/candidate/server/mars_relief /export/gmtserver/gmt/data/server/mars_relief
```

They have to include the name of the **planet**:
```
server/mars_relief         # wrong
server/mars/mars_relief    # OK
```

### Solution

I think I can fix it. 

I am thinking on editing the script. I can add a command that creates the variable `{PLANET}` from `{DATASET}`. Let me know if you are ok with this solution. Or let me know how would you like me to do it.

### PR DESCRIPTION
**Pull request by Esteban82**
Fixes #222

### CODE REVIEW

**Comment by Esteban82** [comment]
Ready for review.

**Comment by Esteban82** [comment]
I add WIP because I think that there is another issue.

**Review by PaulWessel — APPROVED** [review]
Make sure DATASET is empty if you don’t specify a dataset.

**Comment by Esteban82** [comment]
@PaulWessel this doesn't look well.

 2c. Count the number of data files or directory entries and start first line of /tmp/gmt_data_server.txt:

```
cat $(cat /tmp/datasets.lis) | grep -v '^#' | wc -l | awk '{printf "%d\n", }' > /tmp/gmt_data_server.txt
awk: cmd. line:1: {printf "%d\n", }
awk: cmd. line:1:                 ^ syntax error
awk: cmd. line:1: {printf "%d\n", }
awk: cmd. line:1:                  ^ unexpected newline or end of string

```

**Comment by Esteban82** [comment]
Should I add `$0`? 

`cat $(cat datasets.lis) | grep -v '^#' | wc -l  | awk '{printf "%d\n", $0 }' > gmt_data_server.txt`

**Comment by PaulWessel** [comment]
Should be $1 not 0

**Comment by Esteban82** [comment]
Yes, I found the error.

**Comment by Esteban82** [comment]
Here I can't find the header.
```
# 2d. Append the header information section after piping via sed to get the date
cat /export/gmtserver/gmt/gmt_data_server_header.txt | sed -f /tmp/sed.txt >> /tmp/gmt_data_server.txt
cat: /export/gmtserver/gmt/gmt_data_server_header.txt: No such file or directory

```

### Solutions:
1) add that file there.
2) use this path instead `/export/gmtserver/gmt/gmtserver-admin/information`

I think 2. is better.

**Comment by PaulWessel** [comment]
I think that is what I programmed, no?  Might have to run git pull to update the gmtserver-admin dir on oceania.

FYI, tomorrow is birthday so will be out for theatre and dinner so dont expect too much feedback until 22-23 hours from now!

**Comment by Esteban82** [comment]
Ok. Enjoy!!

**Comment by Esteban82** [comment]
I think that now is ready for review. 

The only issue remaining is that right now, in Oceania, only `earth_synbath` has the `*_*_server.txt` file. 
So, when I run this: 
`find /export/gmtserver/gmt/data/server -name '*_*_server.txt' > /tmp/datasets.lis`

I only will get that file and this will result that the new `gmt_data_server.txt` only will have the records of `earth_synbath`.

This could be easily solve by:
1. using rsync with all the data sets (this will copy to oceania the dataset of all the other planets).
2. using rsync just for the earth data set ( `rsync -al /export/gmtserver/gmt/candidate/server/earth/ /export/gmtserver/gmt/data/server/earth` ).

I could the 2. What do you think @PaulWessel? Should I proceed?

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
