### PR TITLE
Add earth_mss recipe

### PR DESCRIPTION
**Pull request by Esteban82**

### CODE REVIEW

**Review by PaulWessel — APPROVED** [review]
Looks great!

**Comment by Esteban82** [comment]
When I run it I got these messages for `bash scripts/srv_downsampler.sh earth_mss -f`

```

scripts/srv_downsampler_grid.sh: line 136: [: 167.483: integer expression expected
Convert CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_01m_g.grd=ns+s0.01+o0
NaNs in source: Reformatted from master file earth/earth_mss/earth_mss_01m_g.grd has 54893079 NaNs
NOTE: File earth/earth_mss/earth_mss_01m_g.grd have no reduction in NaNs from the original 54893079 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_02m_g.grd=ns+s0.01+o0 FW = 10.5 km [339s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_02m_g.grd have reduction in NaNs from 54893079 to 13619960 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_02m_p.grd=ns+s0.01+o0 FW = 10.5 km [339s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_02m_p.grd have reduction in NaNs from 54893079 to 13612880 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_03m_g.grd=ns+s0.01+o0 FW = 15.7 km [509s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_03m_g.grd have reduction in NaNs from 54893079 to 6016094 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_03m_p.grd=ns+s0.01+o0 FW = 15.7 km [509s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_03m_p.grd have reduction in NaNs from 54893079 to 6018858 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_04m_g.grd=ns+s0.01+o0 FW = 21 km [679s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_04m_g.grd have reduction in NaNs from 54893079 to 3373534 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_04m_p.grd=ns+s0.01+o0 FW = 21 km [679s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_04m_p.grd have reduction in NaNs from 54893079 to 3370347 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_05m_g.grd=ns+s0.01+o0 FW = 26.2 km [849s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_05m_g.grd have reduction in NaNs from 54893079 to 2149771 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_05m_p.grd=ns+s0.01+o0 FW = 26.2 km [849s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_05m_p.grd have reduction in NaNs from 54893079 to 2147756 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_06m_g.grd=ns+s0.01+o0 FW = 31.5 km [1018s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_06m_g.grd have reduction in NaNs from 54893079 to 1487149 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_06m_p.grd=ns+s0.01+o0 FW = 31.5 km [1018s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_06m_p.grd have reduction in NaNs from 54893079 to 1484968 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_10m_g.grd=ns+s0.01+o0 FW = 52.4 km [1697s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_10m_g.grd have reduction in NaNs from 54893079 to 526774 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_10m_p.grd=ns+s0.01+o0 FW = 52.4 km [1697s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_10m_p.grd have reduction in NaNs from 54893079 to 525558 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_15m_g.grd=ns+s0.01+o0 FW = 78.6 km [2546s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_15m_g.grd have reduction in NaNs from 54893079 to 229599 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_15m_p.grd=ns+s0.01+o0 FW = 78.6 km [2546s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_15m_p.grd have reduction in NaNs from 54893079 to 228818 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_20m_g.grd=ns+s0.01+o0 FW = 104.8 km [3394s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_20m_g.grd have reduction in NaNs from 54893079 to 126602 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_20m_p.grd=ns+s0.01+o0 FW = 104.8 km [3394s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_20m_p.grd have reduction in NaNs from 54893079 to 126085 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_30m_g.grd=ns+s0.01+o0 FW = 157.3 km [5091s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_30m_g.grd have reduction in NaNs from 54893079 to 54246 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_30m_p.grd=ns+s0.01+o0 FW = 157.3 km [5091s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_30m_p.grd have reduction in NaNs from 54893079 to 53910 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_01d_g.grd=ns+s0.01+o0 FW = 314.5 km [10182s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_01d_g.grd have reduction in NaNs from 54893079 to 12167 nodes
Down-filter CNES_CLS_22_H.nc to earth/earth_mss/earth_mss_01d_p.grd=ns+s0.01+o0 FW = 314.5 km [10182s]
grdfilter [WARNING]: (y_max-y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdfilter (gmtapi_init_grdheader): Please select compatible -R and -I values
NOTE: File earth/earth_mss/earth_mss_01d_p.grd have reduction in NaNs from 54893079 to 11981 nodes
```

**Comment by Esteban82** [comment]
And some errors with `bash scripts/srv_tiler.sh earth_mss`

```
Convert subset N71E000 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E000.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E030 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E030.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E060 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E060.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E090 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E090.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E120 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E120.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E150 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E150.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E180 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E180.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E210 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E210.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E240 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E240.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E270 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E270.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E300 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E300.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
Convert subset N71E330 from earth_mss_01m_g.grd to ./earth/earth_mss/earth_mss_01m_g/N71E330.earth_mss_01m_g.jp2
grdconvert [ERROR]: Subset exceeds data domain!
```

**Comment by PaulWessel** [comment]
You have git pulled the latest scripts etc, right? See this error:

`scripts/srv_downsampler_grid.sh: line 136: [: 167.483: integer expression expected`

Is the grid's lon/lat range out of whack? This should be 180. Ah, not going -90/90.  What is grdinfo again?

**Comment by PaulWessel** [comment]
I know what to do: Fill in NaNs. Hold on a few...

**Comment by Esteban82** [comment]
> What is grdinfo again?

```
gmt grdinfo CNES_CLS_22_H.nc 
CNES_CLS_22_H.nc: Title: 
CNES_CLS_22_H.nc: Command: gmt xyz2grd -bi3d -RCNES_CLS_22_H.nc -fg -Gjunk.grd
CNES_CLS_22_H.nc: Remark: 
CNES_CLS_22_H.nc: Gridline node registration used [Geographic grid]
CNES_CLS_22_H.nc: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
CNES_CLS_22_H.nc: x_min: 0 x_max: 360 x_inc: 0.0166666666667 (1 min) name: longitude n_columns: 21601
CNES_CLS_22_H.nc: y_min: -79.4166669828 y_max: 88.0666670172 y_inc: 0.016666666733 (1 min) name: latitude n_rows: 10050
CNES_CLS_22_H.nc: v_min: -105.553001404 v_max: 84.2519989014 name: z
CNES_CLS_22_H.nc: scale_factor: 1 add_offset: 0
CNES_CLS_22_H.nc: format: classic
CNES_CLS_22_H.nc: Default CPT: 
```

**Pull request merged**
