### PR TITLE
Add EMAG2 default CPT

### PR DESCRIPTION
**Pull request by PaulWessel**
This is the CPT used by NEIC for their [EMAG2](https://www.ngdc.noaa.gov/geomag/emag2.html) maps.  I got it from Brian Meyer at NOAA.  As I plan to add _earth_mag_ and _eath_mag4km_ remote grids, like the age grids I want to use @emag2.cpt as the default CPT for this data. It goes into the cache for now.  However, by being tied to a supported server grid, perhaps cache is not a good place for these.  But for now...

### CODE REVIEW

**Review by meghanrjones — APPROVED** [review]
Agree that long-term we should find a better place

**Comment by joa-quim** [comment]
We already have ``mag.cpt`` this one does not seem very different (judging only from the colors on the site). 
EMAG is a lousy magnetic anomalies grid.

**Comment by PaulWessel** [comment]
Well, they are quite different, see the plot.  Also, what other global magnetic grids are there?

cpts

**Comment by joa-quim** [comment]
A mag cpt that goes only to 200 nT for marine magnetic anomalies that often go above 1000 nT. Really.
My original mag.cpt was not normalized. It was like this (which is what I still use)
```
#
# IPGP Color table for mangetic anomaly maps
#------------------------------------------------
# COLOR_MODEL = RGB
# HINGE = 0
# RANGE = -2000/2000
#------------------------------------------------
-2000   0   0 204  -600   0   0 204
 -600   0 153 255  -500   0 153 255
 -500   0 204 255  -400   0 204 255
 -400   0 204 128  -300   0 204 128
 -300   0 204   0  -200   0 204   0
 -200 102 255   0  -100 102 255   0
 -100 150 255   0   -50 150 255   0
  -50 255 255  38     0 255 255  38
    0 255 255  77    50 255 255  77
   50 230 230   0   100 230 230   0
  100 255 204   0   200 255 204   0
  200 255 153   0   300 255 153   0
  300 255 102   0   400 255 102   0
  400 255   0   0   500 255   0   0
  500 204   0   0   600 204   0   0
  600 180   0   0  2000 180   0   0
#------------------------------------------------
B       black
F       245/255/255
N	gray
#----------------------------------------------------------
```

**Comment by joa-quim** [comment]
> Also, what other global magnetic grids are there

Just pointed another: WDMAM

**Comment by PaulWessel** [comment]
> A mag cpt that goes only to 200 nT for marine magnetic anomalies that often go above 1000 nT. Really. My original mag.cpt was not normalized. It was like this (which is what I still use)
> 
> ```
> #
> # IPGP Color table for mangetic anomaly maps
> #------------------------------------------------
> # COLOR_MODEL = RGB
> # HINGE = 0
> # RANGE = -2000/2000
> #------------------------------------------------
> -2000   0   0 204  -600   0   0 204
>  -600   0 153 255  -500   0 153 255
>  -500   0 204 255  -400   0 204 255
>  -400   0 204 128  -300   0 204 128
>  -300   0 204   0  -200   0 204   0
>  -200 102 255   0  -100 102 255   0
>  -100 150 255   0   -50 150 255   0
>   -50 255 255  38     0 255 255  38
>     0 255 255  77    50 255 255  77
>    50 230 230   0   100 230 230   0
>   100 255 204   0   200 255 204   0
>   200 255 153   0   300 255 153   0
>   300 255 102   0   400 255 102   0
>   400 255   0   0   500 255   0   0
>   500 204   0   0   600 204   0   0
>   600 180   0   0  2000 180   0   0
> #------------------------------------------------
> B       black
> F       245/255/255
> N	gray
> #----------------------------------------------------------
> ```

Same as in GMT. Looks the same whether I use original -T or -T-200/200.  We are just scaling the z values.

**Comment by PaulWessel** [comment]
Note yours are really only going -T-600/500 since colors outside that range are constant, so more like B, F settings.

**Comment by PaulWessel** [comment]
> ust pointed another: WDMAM

Thanks, will get that one too.

**Pull request merged**
